databases:
  booking:
    host: "localhost"
    port: 5436
    user: "booking_user"
    password: "booking_pass"
    dbname: "booking_db"
    sslmode: "disable"
  
  hotel:
    host: "localhost"
    port: 5437
    user: "hotel_user"
    password: "hotel_pass"
    dbname: "hotel_db"
    sslmode: "disable"